services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 12181:2181
    volumes:
      - zookeeper_data_1:/data
      - zookeeper_log_1:/datalog
    networks:
      - kafkanet
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181


  mykafka1:
    image: mykafka
    hostname: mykafka
    container_name: mykafka
    networks:
      - kafkanet
    ports:
      - 19094:19094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://mykafka:9092,EXTERNAL://mykafka:19094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://mykafka:9092,EXTERNAL://${MYKAFKA}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LOG_DIRS: /root/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data_1:/root/kafka/data
      - kafka_log_1:/root/kafka/logs
    depends_on:
      - zoo1



volumes:
  zookeeper_data_1:
  zookeeper_log_1:
  kafka_data_1:
  kafka_log_1:

networks:
  kafkanet:
