services:
  producer:
    image: myproducer
    hostname: myproducer
    container_name: myproducer
    volumes:
      - ../app:/root/maple/app
    environment:
      PYTHONPATH: /root/maple
      MYKAFKA: ${MYKAFKA}
      MAPLE_API_KEY: ${MAPLE_API_KEY}
    working_dir: /root/maple
